#!/usr/bin/env bash

# Launch executable provided as an argument
# SIGSTOP it as soon as possible
$1 >&2 &
workload_pid=$!
sleep 0.1 && kill -STOP $workload_pid

echo $workload_pid
echo Workload PID: $workload_pid >&2

# Wait for SIGUSR1
function set_sigusr1_received {
	sigusr1_received=1
}
trap set_sigusr1_received SIGUSR1
sigusr1_received=0
while [ $sigusr1_received -eq 0 ] ; do
	sleep 0.5
done

# Resume and join the workload process
kill -CONT $workload_pid
wait $workload_pid
